# Dev config
-
  branches:
    only:
      - /[Dd]ev/
  version: 1.0.0-alpha-{build}
  configuration: Release
  image: Visual Studio 2017 Preview
  services:
    - mssql2016
  nuget:
    account_feed: false
    project_feed: false
    disable_publish_on_pr: true
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    APPVEYOR_BUILD_VERSION:  1.0.0-alpha-{build}
    NUGET_API_KEY:
        secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
  init:
  - ps: $Env:LABEL = "alpha-" + $Env:APPVEYOR_BUILD_NUMBER
  before_build:
  - ps: >-
      $Env:LABEL

      $Env:APPVEYOR_BUILD_VERSION

      C:\Tools\nuget\nuget.exe update -self

      nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json;

      appveyor-retry dotnet restore -v Minimal;
  build_script:
  - dotnet build "src\Arragro.Core.Common" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "src\Arragro.Core.EntityFrameworkCore" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "src\Arragro.Core.Web" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "src\Arragro.Core.DistributedCache" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "src\Arragro.Core.Identity" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "providers\Arragro.Providers.AzureStorageProvider" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "providers\Arragro.Providers.ImageMagickProvider" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "providers\Arragro.Providers.ImageServiceProvider" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "providers\Arragro.Providers.InMemoryStorageProvider" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "providers\Arragro.Providers.MailKitEmailProvider" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  - dotnet build "providers\Arragro.Providers.SendgridEmailProvider" -c %CONFIGURATION% --no-dependencies /p:Version=%APPVEYOR_BUILD_VERSION%
  test_script:
  - dotnet test "tests\Arragro.Core.Common.Tests\Arragro.Core.Common.Tests.csproj" -c %CONFIGURATION%
  - dotnet test "tests\Arragro.Core.EntityFrameworkCore.IntegrationTests\Arragro.Core.EntityFrameworkCore.IntegrationTests.csproj" -c %CONFIGURATION%
  test: on
  artifacts:  
    - path: .\artifacts\**\*.nupkg
      name: NuGet
  before_deploy:
    - dotnet pack "src\Arragro.Core.Common" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "src\Arragro.Core.EntityFrameworkCore" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "src\Arragro.Core.Web" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "src\Arragro.Core.DistributedCache" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "src\Arragro.Core.Identity" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "providers\Arragro.Providers.AzureStorageProvider" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "providers\Arragro.Providers.ImageMagickProvider" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "providers\Arragro.Providers.ImageServiceProvider" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "providers\Arragro.Providers.InMemoryStorageProvider" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "providers\Arragro.Providers.MailKitEmailProvider" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
    - dotnet pack "providers\Arragro.Providers.SendgridEmailProvider" -c %CONFIGURATION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%\artifacts
  deploy_script:
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Core.Common.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Core.EntityFrameworkCore.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Core.Web.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Core.DistributedCache.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Core.Identity.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Providers.AzureStorageProvider.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Providers.ImageMagickProvider.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Providers.ImageServiceProvider.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Providers.InMemoryStorageProvider.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Providers.MailKitEmailProvider.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
    - dotnet nuget push %APPVEYOR_BUILD_FOLDER%\artifacts\Arragro.Providers.SendgridEmailProvider.%APPVEYOR_BUILD_VERSION%.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY%
#  deploy:
#  - provider: NuGet
#    api_key:
#      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
#    project_feed: true
  notifications:
  - provider: Webhook
    url:
      secure: /Mu5qzDWowMVA/HgNRKsFIRzdiAM8fWBT/i5SAyUJuLqehc92nC0PczXziza/Q6M4f91rrUq/19dzG36gpWnAN0tDvXnQE+bXyvR22woKNLC3fpbitLOwgAgV2iaDzNm6EQ8+R+y0a9BrPikNVucKeRygbA/vIsX24XkVTp5qWyP26ONeoJDJ5SUcTeYIMHFAj4XxgFjfmdwSWp623h9VWPXnjgEGiQO0xwfL2MI4bA=
    method: POST
    content_type: 
    body: >-
      payload={
          "text": "AppVeyor Build {{projectName}} - {{buildVersion}} on branch {{branch}} by by {{commitAuthor}} {{#passed}}passed{{/passed}}{{#failed}}failed{{/failed}} ({{started}} - {{finished}})"
      }
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true