# Dev config
-
  branches:
    only:
      - /[Dd]ev/
  version: 1.0.0-alpha-{build}
  configuration: Release
  image: Visual Studio 2017
  services:
    - mssql2016
  nuget:
    account_feed: false
    project_feed: false
    disable_publish_on_pr: true
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: $(appveyor_build_version)
    assembly_file_version: $(appveyor_build_version)
    assembly_informational_version: $(appveyor_build_version)
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    appveyor_build_version:  1.0.{build}
  init:
  - ps: $Env:LABEL = "alpha-build" + $Env:APPVEYOR_BUILD_NUMBER
  - ps: $Env:LABEL
  - ps: $Env:appveyor_build_version = "1.0." + $Env:APPVEYOR_BUILD_NUMBER
  - ps: $Env:appveyor_build_version
  before_build:
  - ps: >-
      $Env:LABEL

      C:\Tools\nuget\nuget.exe update -self

      nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json;

      appveyor-retry dotnet restore -v Minimal;

      nuget install redis-64 -excludeversion;

      redis-64\tools\redis-server.exe --service-install;

      redis-64\tools\redis-server.exe --service-start;
  test: on
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    project_feed: true
  notifications:
  - provider: Slack
    incoming_webhook:
      secure: bjVXknaXcfc36i0/LExrNgcKan16rpet77LF5ik15h1erCbSEawuDkD92PcFeeFKQkeHtxYlST34GO51sLtwzN/V+LKTGg+KXH+uDcmqRgE=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true